# Generated by Django 3.2.4 on 2022-02-01 15:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costs', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='type_of_food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('address', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('website', models.URLField(verbose_name='URL')),
                ('description', models.TextField(default='nothing')),
                ('late_hours', models.BooleanField(default=False, verbose_name='Opens After 10pm')),
                ('cuisine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food.cuisine')),
                ('price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food.price')),
                ('type_of_food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food.type_of_food')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
