# Generated by Django 3.2.4 on 2022-04-26 10:28

from django.db import migrations, models
import food.utils


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': (['name'],)},
        ),
        migrations.AddField(
            model_name='shop',
            name='Referrence_Number',
            field=models.CharField(blank=True, default=food.utils.create_new_ref_number, editable=False, max_length=10, unique=True),
        ),
        migrations.AddConstraint(
            model_name='shop',
            constraint=models.UniqueConstraint(fields=('user', 'Referrence_Number'), name='user_Referrence_Number'),
        ),
    ]
