# Generated by Django 3.2.4 on 2022-04-26 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20220426_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={},
        ),
    ]
