# Generated by Django 3.2.4 on 2022-02-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20220209_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='directions',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
