# Generated by Django 3.2.4 on 2022-04-26 11:09

from django.db import migrations, models
import food.utils


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20220426_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='referrence_Number',
            field=models.CharField(blank=True, default=food.utils.create_new_ref_number, max_length=10),
        ),
    ]
