# Generated by Django 3.2.4 on 2022-02-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20220211_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='halal',
            field=models.BooleanField(default=False, verbose_name='Halal'),
        ),
    ]
