# Generated by Django 3.2.4 on 2022-05-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_shop_referrence_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='cover',
            field=models.ImageField(default='', upload_to='cover_images/'),
            preserve_default=False,
        ),
    ]
