# Generated by Django 3.2.4 on 2022-05-12 12:00

import ckeditor.fields
from django.db import migrations, models
import food.utils
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('food', '0006_shop_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='cover',
            field=models.ImageField(blank=True, upload_to='cover_images/'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='nothing'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='referrence_Number',
            field=models.CharField(blank=True, default=food.utils.create_new_ref_number, editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='shop',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
