# Generated by Django 3.2.4 on 2022-02-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_shop_halal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='halal',
            field=models.BooleanField(default=False, verbose_name='Halal'),
        ),
    ]
