# Generated by Django 4.2.2 on 2023-08-08 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_auto_20220601_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='tags',
        ),
    ]
