# Generated by Django 3.2.4 on 2022-03-29 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_auto_20220329_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='opening_times',
        ),
        migrations.DeleteModel(
            name='OpeningTime',
        ),
    ]
