# Generated by Django 3.2.4 on 2022-04-18 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_shop_open_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='open_hours',
        ),
    ]
